name: Action workflow test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ test-api, test-consumer]
    
    steps:
      - name: set dir name
        run: |
          SERVICE=service-${{ matrix.service }}-eks
          DIR_NAME="${SERVICE//-api-eks/-api}"
          echo $DIR_NAME
